version: "3.9"
services:
  rewards-postgress:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_MULTIPLE_DATABASES: "rewards-config"
      
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test_records_calculator@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"